<?php

namespace Modules\Admin\Repositories\Posts;

use Illuminate\Database\Eloquent\Builder;

trait PostsCriteria
{
    public function apply($model)
    {
        $builder = $model->where('post_type', 'post');
        return $builder; // TODO: Change the autogenerated stub
    }

    protected function postFilterByRequest(Builder $query)
    {
        $query->with('category_id', 'attributes');
        return parent::postFilterByRequest($query);
    }
}
