<?php

namespace Modules\Admin\Repositories\Pages;

trait PagesCriteria
{
    public function apply($model)
    {
        $builder = $model->where('post_type', 'page');
        if (!user_get()->is_super_admin) {
            $builder = $builder->whereNotIn('id', [1, 263]);
        }
        //
        return $builder; // TODO: Change the autogenerated stub
    }
}
