<?php

namespace Modules\Admin\Repositories\News;

trait NewsCriteria
{
    public function apply($model)
    {
        $builder = $model
            ->select(['posts.*', 'category_id'])
            ->leftJoin('post_categories', 'post_categories.post_id', '=', 'posts.id')
            ->where('post_type', 'news');
        return $builder; // TODO: Change the autogenerated stub
    }
}
